### ISSUE TITLE
Audiocodes SBC ERROR failed parsing Outgoing SIP. Cache on!

### ISSUE THREAD

**Issue by Wolffis** [sipcapture/paStash#76] opened 2021-01-07 13:06 UTC
Hi, tried the paStash with Audiocodes SBC thing to get syslogs to Homer, but no luck so far. When I redirect the syslog from Audiocodes Mediant SW SBC to paStash IP, I see the traffic incoming and at the same time massive amount of 

ERROR failed parsing Outgoing SIP. Cache on!

as paStash output and nothing going over to the 9060 Homer port. All settings default from the guide. Any idea what that error means?

Thanks for the help!

**Comment by lmangani** [comment] 2021-01-08 13:41
The message parser does not seem to find any terminators and keeps merging events looking for one ad infinitum. This could be some difference in the syslog format between SBC version or just about any other reason, would need to see some of the traffic being processed. Please enable the debug flag and show us some of the output and/or capture some samples of the syslog events to look at to find out :)

**Comment by Wolffis** [comment] 2021-01-13 08:18
Here's the debug from paStash and incoming syslog from Audiocodes (10.250.39.14) as an attachment (tcpdump pcap from the paStash/Homer server 10.250.39.120). Only thing I have tried to change is the syslog debug level in Audiocodes between Basic and Extended, but that won't change anything as the SIP messages are the same in both.

# pastash --config_file=/usr/local/etc/pastash/pastash_sonus.conf --log_level debug
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Changing log_level debug
[Wed, 13 Jan 2021 07:42:02 GMT] NOTICE Starting pastash 1.0.71
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Max http socket 100
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Loading config file : /usr/local/etc/pastash/pastash_sonus.conf
[Wed, 13 Jan 2021 07:42:02 GMT] INFO File loaded, 3 urls found
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Loading config : 6 urls
[Wed, 13 Jan 2021 07:42:02 GMT] DEBUG Loading urls [ 'filter://add_host://',
  'filter://add_timestamp://',
  'filter://add_version://',
  'input://udp://?host=0.0.0.0&port=514&type=syslog',
  'filter://app_audiocodes://',
  'output://hep://?host=127.0.0.1&port=9060&hep_id=2222&__dynamic_eval__=%7B%22false_clauses%22%3A%5B%5D%2C%22true_clause%22%3A%7B%22op%22%3A%22!%3D%22%2C%22left%22%3A%7B%22field%22%3A%22rcinfo%22%7D%2C%22right%22%3A%7B%22value%22%3A%22undefined%22%7D%7D%7D' ]
[Wed, 13 Jan 2021 07:42:02 GMT] DEBUG Initializing module output
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Initializing output HEP/EEP Server
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Start output to HEP udp to 127.0.0.1:9060
[Wed, 13 Jan 2021 07:42:02 GMT] DEBUG Initializing module filter
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Initializing filter AddHost
[Wed, 13 Jan 2021 07:42:02 GMT] DEBUG Initializing module filter
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Initializing filter AddTimestamp
[Wed, 13 Jan 2021 07:42:02 GMT] DEBUG Initializing module filter
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Initializing filter AddVersion
[Wed, 13 Jan 2021 07:42:02 GMT] DEBUG Initializing module filter
[Wed, 13 Jan 2021 07:42:02 GMT] DEBUG no local module found filters filter_app_audiocodes { Error: Cannot find module 'filters/filter_app_audiocodes'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at LogstashAgent.configure (/usr/local/lib/node_modules/@pastash/pastash/lib/agent.js:133:17)
    at LogstashAgent.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/agent.js:215:10)
    at /usr/local/lib/node_modules/@pastash/pastash/node_modules/async/dist/async.js:3096:16
    at replenish (/usr/local/lib/node_modules/@pastash/pastash/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/usr/local/lib/node_modules/@pastash/pastash/node_modules/async/dist/async.js:983:17)
    at /usr/local/lib/node_modules/@pastash/pastash/node_modules/async/dist/async.js:958:16 code: 'MODULE_NOT_FOUND' }
Loading npm module... @pastash/filter_app_audiocodes
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Initializing filter AppAudiocodes
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Initialized App Audiocodes SysLog to SIP/HEP parser
[Wed, 13 Jan 2021 07:42:02 GMT] DEBUG Initializing module input
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Initializing input Udp
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Start listening on udp 0.0.0.0:514
[Wed, 13 Jan 2021 07:42:02 GMT] INFO Config loaded.
[Wed, 13 Jan 2021 07:42:29 GMT] ERROR failed parsing Outgoing SIP. Cache on!
[Wed, 13 Jan 2021 07:42:29 GMT] ERROR failed parsing Outgoing SIP. Cache on!
[Wed, 13 Jan 2021 07:42:29 GMT] ERROR failed parsing Outgoing SIP. Cache on!
[Wed, 13 Jan 2021 07:42:29 GMT] ERROR failed parsing Outgoing SIP. Cache on!
[Wed, 13 Jan 2021 07:42:30 GMT] ERROR failed parsing Outgoing SIP. Cache on!
.
.
.

**Comment by lmangani** [comment] 2021-01-13 12:56
Could you try the following recipe and paste its output? this is basically a dumb syslog to console collector which should allow us to identify the issue quicker within the realm of pastash:
```
input {
  udp {
    host => 0.0.0.0
    port => 514
    type => syslog
  }
}

output {
  stdout {}
}
```

only a few dozen lines should be sufficient to assess the input type. Thanks!

**Comment by Wolffis** [comment] 2021-01-14 07:52
Here's the console output with some OPTIONS and one INVITE test call.

**Comment by lmangani** [comment] 2021-01-14 09:40
Thanks! this looks quite different from other examples users have provided indeed, and will need some parser tweaking to succeed - what's the software version and settings of the SBC sending the syslog?

**Comment by Wolffis** [comment] 2021-01-14 10:09
Audiocodes Mediant SW SBC (Virtual Edition) 7.20A.204.838

Settings:
Enabled
IP
514
Syslog CPU Proctection: Enabled
Syslog Optimazation: Disabled
Debug Level: Basic

Activity Types to Report: All checked

Here's the syslog guide, chapter 5 seems to define things pretty extensively:
https://www.audiocodes.com/media/14787/syslog-viewer-users-guide.pdf

Here's the SBC manual, 57.2 (page 874) describes the parameters:
https://www.audiocodes.com/media/13248/mediant-software-sbc-users-manual-ver-72.pdf

**Comment by lmangani** [comment] 2021-01-14 11:41
@spady7 got this working. Could you share your SBC syslog config here please?

**Comment by spady7** [comment] 2021-01-15 12:59
Hi, i've same settings apart Debug Level. I have "Detailed".

**Comment by Wolffis** [comment] 2021-01-15 13:53
And detailed should only increase the amount of lines for internal processing information which is not useful from Homer SIP trace perspective. Basic and Detailed have the same error for me.

So the syslog format in my case is different and e.g. my paStash installation as such seems to be working?

**Comment by os11k** [comment] 2021-01-16 10:21
Hi! I have same problem, a lot of "ERROR failed parsing Incoming SIP. Cache on!"

Version ID:  7.20A.256.511

Here is my pastash config:

```
input {
  udp {
    host => 0.0.0.0
    port => 10514
    type => syslog
  }
}

filter {
  app_audiocodes {
    autolocal => true
    qos => true
  }
}

output {
  if [rcinfo] != 'undefined' {
        hep {
          host => '10.182.151.163'
          port => 9060
          hep_id => 100
          hep_type => 1
        }
  }
}
```


Syslog settings:
Enable Syslog: Enable
Syslog Server IP: 10.10.151.163
Syslog Server Port: 10514
Log Severity Level: Debug
Syslog CPU Protection: Enabled
Syslog Optimization: Disabled
VoIP Debug Level: Detailed
Debug Level High Threshold: 90
Activity Types to Report: All checked

@spady7 can you share your pastash config and what is your Audiocodes version and Audiocodes Syslog settings?

@lmangani can you please look into this too? :)

Thank you!

**Comment by spady7** [comment] 2021-01-18 08:13
Hi all, 
Audiocodes version : 7.20A.260.012
Syslog settings:
![Schermata 2021-01-18 alle 09 11 48](https://user-images.githubusercontent.com/31621633/104888636-4d698380-596d-11eb-8783-6b8815a5500f.png)
`input {
  udp {
    host => 0.0.0.0
    port => 514
    type => syslog
  }
}

filter {
  app_audiocodes {
    autolocal => true
    qos => true
  }
}

output {
  stdout{}
  if [rcinfo] != 'undefined' {
        hep {
          host => '10.160.21.80'
          port => 9069
          hep_id => 100
          hep_type => 1
        }
  }
}`

And here result:

![Schermata 2021-01-18 alle 09 07 40](https://user-images.githubusercontent.com/31621633/104888788-89044d80-596d-11eb-8211-52200076ba68.png)

**Comment by os11k** [comment] 2021-01-18 08:42
Thank you @spady7 , I have identical settings in Audiocodes and config is almost same too, only you have  stdout{}, what I believe is not important.

I'm still getting "ERROR failed parsing Incoming SIP. Cache on!"

**Comment by lmangani** [comment] 2021-01-18 08:47
Thanks @spady7 for confirming this works. @os11k @Wolffis I will try to have a look at your logs in the coming days but no guarantees as this will be a huge investment of time - feel free to donate or help out our project if you'd like this ramped up in priority.

**Comment by os11k** [comment] 2021-01-18 16:39
Hi!

I think I fixed this problem for my Audiocodes, seems different versions should use different Regex. I'm preparing pull request with my changes. Meanwhile @spady7 do you see SDP in your Invite in Homer? I suspect that it is empty. Could you please recheck? If not I will update Regex for your version too.

**Comment by lmangani** [comment] 2021-01-18 17:03
Thanks @os11k for stepping in! the current regex was modelled over a single example set so any patches are super appreciated!
Unless you already have done so, we can add a `version` parameter to the plugin in order to support multiple releases.

**Comment by os11k** [comment] 2021-01-18 18:13
Hi @lmangani !

I created pull request, seems I didn't break anything. :) I'm not really js developer, but I think this is something what I can fix.

@Wolffis can you check if my changes works for you too, if not I can try to fix for you too, while I do remember what is where.

**Comment by lmangani** [comment] 2021-01-19 11:38
Thanks @os11k for your contribution and support! Patches have been merged, configuration updated and npm published
```
+ @pastash/filter_app_audiocodes@1.0.25
```

Any feedback welcome - @spady7 could you check if this works on your system? Note the new `version` parameter in readme

**Comment by os11k** [comment] 2021-01-19 16:37
I just tested paStash with Audiocodes 7.20A.258.271 and it seems to work too. It use same regex as "7.20A.256.511", so version in conifg should be 7.20A.256.511

**Comment by os11k** [comment] 2021-01-19 16:47
I just connected 2 Audiocodes to write data to 1 pastash and everything is ok, except now in homer this 2 Audiocodes are getting same IP. Any ideas how to fix it? In logstash there is pipelines for this, as far as I remember

**Comment by os11k** [comment] 2021-01-19 17:33
Actually I found solution, sorry for noise. :)

```
input {
  udp {
    host => 0.0.0.0
    port => 10514
    type => syslog
    tags => ["10514"]
  }
  udp {
    host => 0.0.0.0
    port => 10515
    type => syslog
    tags => ["10515"]
  }
}

filter {
  if "10514" in [tags] {
  app_audiocodes {
    debug => true
    autolocal => true
    qos => true
    localip => 10.10.56.13
  }
  }
  if "10515" in [tags] {
  app_audiocodes {
    debug => true
    autolocal => true
    qos => true
    localip => 10.43.56.13
  }
  }

}

output {
  if [rcinfo] != 'undefined' {
        hep {
          host => '10.182.151.163'
          port => 9060
          hep_id => 100
          hep_type => 1
        }
  }
}
```

**Comment by lmangani** [comment] 2021-01-19 17:45
This is great! you're using paStash as it's supposed to :) I might add this to the wiki its a great example!
As of the version, I documented as `lower` and `higher` versions should be fine unless otherwise proven.

Any reason you are forcing `hep_type` in the output? This might prevent actual logs and potential media reports from working

hep_type 1 is exclusively for SIP, but the parser should also able to ship out type 5 and type 100 when data is available.

**Comment by os11k** [comment] 2021-01-19 17:49
I just copied some example what I saw somewhere here. :) Let me try without  `hep_type` :)

**Comment by lmangani** [comment] 2021-01-19 17:51
Wiki has been updated: https://github.com/sipcapture/paStash/wiki/Example:-AUDIOCODES-Syslog

**Comment by lmangani** [comment] 2021-01-19 17:52
Without the `hep_type` forced you might also see Logs and QoS RTCP reports (very experimental) for your calls

**Comment by lmangani** [comment] 2021-01-19 18:01
Closing this as successful! Feel free to comment further if needed or useful, and thanks again for the contribution!

**Closed as completed by lmangani** 2021-01-19 18:01 UTC

**Comment by spady7** [comment] 2021-01-20 14:13
> Hi!
> 
> I think I fixed this problem for my Audiocodes, seems different versions should use different Regex. I'm preparing pull request with my changes. Meanwhile @spady7 do you see SDP in your Invite in Homer? I suspect that it is empty. Could you please recheck? If not I will update Regex for your version too.

Hi @os11k
sorry for big delay but i was out of office. Great to see the big work you and Lorenzo done! I've gave a try and multiple SBC (I also tried with an MP114) and works. 
Replying to your question, i can't see SDP part. 
Do you?

**Comment by os11k** [comment] 2021-01-20 17:46
Hi @spady7 ! That what I thought when I saw regex what is used for your version. Maybe you can share with me log for such kind of INVITE? I'm interested in one line what starts with `reassembled line` and has that INVITE what you see in homer without SDP, or you can share full file.

**Comment by lmangani** [comment] 2021-01-20 17:50
Let's open a new issue for this so we can track it properly? I suppose the problem is we seek a double newline. Will check it as well.
